config/routes.rb
Rails.application.routes.draw do


  root to: 'books#index'

  resources :users, only: [:index, :show, :new, :edit, :update]

  resources :books, only: [:index, :show]

  resources :sessions, only: [:create]

  resources :bookstores, only: [:index]


  resource :favourites, only: [:show] do
    put    :add_item
  end

  resource :wishlist, only: [:show, :index] do
    put     :add_book
    delete  :remove_book
  end

  namespace :user do
    root to: 'users#show'
  end

  get '/login' => 'sessions#new'
  get '/classics' => 'classics#show'
  get '/provinces' => 'provinces#index'
  get '/feature/author' => 'featureds#index'
  get '/feature/publisher' => 'featureds#show'
  get '/search' => 'searches#search'


  post '/users' => 'users#index'
  get 'search' => 'books#search'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/users' => 'users#index'
  get '/users/:user_id' => 'users#show'
  get '/users/:user_id/edit' => 'users#edit'
  get '/users/:id/wishlist' => 'wishlists#show'

  get 'favourites/favourites'
  get '/bookstores' => 'bookstores#index'

  get '/wishlist' => 'wishlist#show'


  get '/classics' => 'classics#show'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  #belongs_to :author

  acts_as_favable

  has_one :pub_date
  has_many :genre
  has_one :publisher

  def average_rating
  	average = comments.map(&:rating)
  	average.reduce(:+) / average.size.to_f
  end

  def fave
  favable = Model.create
  favable.favorites.create(:url => "<%= book.image_link(:zoom => 5)")
  end

  def show
    favable = Model.find(1)
    favorites = favable.favorites.recent.limit(10).all
  end
end

app/models/bookstore.rb
class Bookstore < ApplicationRecord

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  has_many :books

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  #mount_uploader :image, ProductImageUploader

  has_many :books

  #belongs_to :bookclub

  #has_one :wishlist

  has_one :profile

  validates :username, presence: true
  validates :email, presence: true
  # validates :location, presence: true

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

  belongs_to :user
  has_many :line_items

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @newest_books = GoogleBooks.search('Atlantic Canada',
                  {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc",
                    :count => 20,
                    :order_by => 'newest',
                    :order_by => 'relevance'})
  end

  def show

  end
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def show
    @fiction_ns = GoogleBooks.search('"Nova Scotia", subject: fiction',
                {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc",
                  :count => 10})
    @nonfiction_ns = GoogleBooks.search('"Nova Scotia", subject: fiction',
                {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc",
                  :count => 10})

  end
end

app/controllers/home_controller.rb
# class GoogleBooksController < ActionController::Base
class HomeController < ApplicationController

  def index
  # @googlebooks = GoogleBooks.all
  puts 'ahhhhH!H!H!H'
    @newest_books = GoogleBooks.search('Nova Scotia', {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc", :order_by => 'newest'})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @user = User.all
    #@user.profilePic="../public/default-profile.png" if @user.avatar.empty?
    #order by how many books own/read?
  end

  def show
    @user = User.find(params[:id])
    #@user.profilePic="../public/default-profile.png" if @user.avatar.empty?
  end

  # def profile
  #   @user = User.find params[:id]
  #   #@review = Review.new
  #   #@reviews = @book.reviews
  # end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Read Atlantic"
      redirect_to '/login'
    else
      redirect_to '/register'

    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your changes have been saved"
      redirect_to @user
    else
      render 'edit'

    end
  end

  private

  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation)
  end

  def logged_in_user
    unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to '/login'
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to '/login' unless current_user?(@user)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/end_user_base_helper.rb
module EndUserBaseHelper
end

app/helpers/featureds_helper.rb
module FeaturedsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/books/index.html.erb
<div>
<div class="jumbotron">
  <div class="container">
  <img style="float: left; max-height: 200px; max-width: 200px;" src="ReadAtlanticSymbol.png" />
    <h1 class="display-3">Welcome to Read Atlantic</h1>
    <p class="lead">Find great books written by, published by, and about Atlantic Canadians</p>
  </div>
</div>

<div id="wrapper">
  <div id="columns">

<!--     <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <div>
    <h1 class="page-header">Search by genre</h1>
        <%= form_tag books_path, method: "get", html: { class: "form" } do %>
     <div class="form-group col-xs-4">
       <%= text_field_tag(:subject, "", class: "form-control") %>
     </div>
     <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
      </div>
      <br> -->

      <br>
    <div>
    <h2>New and Noteworthy</h2>
  <% @newest_books.each do |book| %>
    <article class="pin">
      <img src="<%= book.image_link(:zoom => 5) %>" />
        <a href="<%= book.info_link %>" target="_blank"><h4 class="title"><%= book.title %></h4></a>
         <p>by <%= book.authors %></p>
        <p class="cat"><%= book.publisher %>
        <br>
        <%= book.categories %></p>
        <br>
        <%= link_to "Add to Favorites" %>
        <br>
        <%= link_to "Add to Wishlist" %>
      </article>
     <% end %>
    </div>
  </div>
</div>
</div>

app/views/books/show.html.erb
<div>

<section class="books-show">

  <header class="page-header">
    <h1><%= link_to @book.genre.name, @book.genre %> &raquo; <%= @book.name %></h1>
  </header>

  <article class="book-detail">

    <div class="row">

      <div class="col-sm-4">
        <%= image_tag @book.image.url, class: 'main-img' %>
      </div>

      <div class="col-sm-8">
        <dl class="dl-horizontal">
          <dt>Name</dt>
          <dd><%= @book.name %></dd>
          <dt>Description</dt>
          <dd><%= @book.description %></dd>
          <dt>Quantity</dt>
          <dd><%= @product.author %></dd>
          <dt>Price</dt>
          <dd><%= @product.publish_date %></dd>
          <dt>Avg. Rating</dt>
          <dd><%=@book.average_rating %></dd>

        </dl>
      </div>
          <% if current_user %>
            <div>
              <%= form_for [@book, @review] do |f| %>
              <%= f.text_area :content %>
              <%= f.select :rating, options_for_select([[1], [2], [3], [4], [5]]) %> Stars
              <%= f.submit "Create"%>
              <% end %>
            </div>
          <% else %>
            <span>
              <%= link_to 'Login', '/login' %> or <%= link_to 'Signup', '/signup' %> to write a review.
            </span>
          <% end %>
      <div class="col-sm-8">
        <dl class="dl-vertical">
          <dd><%= render "books" %></dd>
        </dl>
      </div>


  </article>

</section>
</div>