config/routes.rb
Rails.application.routes.draw do


  root to: 'books#index'

  resources :users, only: [:index, :show, :new, :edit, :update]

  resources :books, only: [:index, :show]

  resources :sessions, only: [:create]

  resources :bookstores, only: [:index]


  resource :favourites, only: [:show] do
    put    :add_item
  end

  resource :wishlist, only: [:show, :index] do
    put     :add_book
    delete  :remove_book
  end

  namespace :user do
    root to: 'users#show'
  end

  get '/login' => 'sessions#new'
  get '/classics' => 'classics#show'
  get '/provinces' => 'provinces#index'
  get '/feature/author' => 'featureds#index'
  get '/feature/publisher' => 'featureds#show'
  get '/search' => 'searches#search'


  post '/users' => 'users#index'
  get 'search' => 'books#search'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/users' => 'users#index'
  get '/users/:user_id' => 'users#show'
  get '/users/:user_id/edit' => 'users#edit'
  get '/users/:id/wishlist' => 'wishlists#show'

  get 'favourites/favourites'
  get '/bookstores' => 'bookstores#index'

  get '/wishlist' => 'wishlist#show'


  get '/classics' => 'classics#show'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  #belongs_to :author

  acts_as_favable

  has_one :pub_date
  has_many :genre
  has_one :publisher

  def average_rating
  	average = comments.map(&:rating)
  	average.reduce(:+) / average.size.to_f
  end

  def fave
  favable = Model.create
  favable.favorites.create(:url => "<%= book.image_link(:zoom => 5)")
  end

  def show
    favable = Model.find(1)
    favorites = favable.favorites.recent.limit(10).all
  end
end

app/models/bookstore.rb
class Bookstore < ApplicationRecord

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  has_many :books

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  #mount_uploader :image, ProductImageUploader

  has_many :books

  #belongs_to :bookclub

  #has_one :wishlist

  has_one :profile

  validates :username, presence: true
  validates :email, presence: true
  # validates :location, presence: true

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

  belongs_to :user
  has_many :line_items

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @newest_books = GoogleBooks.search('Atlantic Canada',
                  {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc",
                    :count => 20,
                    :order_by => 'newest',
                    :order_by => 'relevance'})
  end

  def show

  end
end

app/controllers/home_controller.rb
# class GoogleBooksController < ActionController::Base
class HomeController < ApplicationController

  def index
  # @googlebooks = GoogleBooks.all
  puts 'ahhhhH!H!H!H'
    @newest_books = GoogleBooks.search('Nova Scotia', {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc", :order_by => 'newest'})
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :logged_in_user, only: [:edit, :update]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def index
    @user = User.all
    #@user.profilePic="../public/default-profile.png" if @user.avatar.empty?
    #order by how many books own/read?
  end

  def show
    @user = User.find(params[:id])
    #@user.profilePic="../public/default-profile.png" if @user.avatar.empty?
  end

  # def profile
  #   @user = User.find params[:id]
  #   #@review = Review.new
  #   #@reviews = @book.reviews
  # end

  def create
    @user = User.create(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome to Read Atlantic"
      redirect_to '/login'
    else
      redirect_to '/register'

    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Your changes have been saved"
      redirect_to @user
    else
      render 'edit'

    end
  end

  private

  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation)
  end

  def logged_in_user
    unless session[:user_id]
      flash[:danger] = "Please log in."
      redirect_to '/login'
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to '/login' unless current_user?(@user)
  end

end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController

  def show
    # @wishlist = Wishlist.find(params[:id])
    # @line_items = @wishlist.line_items
    @wishlist_total = 0
    # book_id = params[:book_id]
    # @wishlist_book = wishlist[book_id]
    @user = User.find(params[:id])
  end

  def add_book
    book_id = params[:product_id].to_s

    item = wishlist[book_id] || {"quantity" => 0}
    item["quantity"] += 1
    wishlist[book_id] = item
    update_wishlist wishlist

    redirect_to :back
  end

  def remove_item
    book_id = params[:book_id].to_s

    item = wishlist[book_id] || {"quantity" => 1}
    item["quantity"] -= 1
    wishlist[book_id] = item
    wishlist.delete(book_id) if item["quantity"] < 1
    update_wishlist wishlist

    redirect_to :back
  end

  def wishlist_total
    total = 0
    wishlist.each do |book_id, details|
      if book_id = Book.find_by(id: product_id)
        total += details['quantity'].to_i
      end
    end
    total
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/end_user_base_helper.rb
module EndUserBaseHelper
end

app/helpers/featureds_helper.rb
module FeaturedsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/wishlists/_item.html.erb
<% quantity = details['quantity'].to_i %>

<% if book = Book.find_by(id: book_id) %>
  <% item_total = quantity %>
  <% @wishlist_total += item_total %>

  <tr>
    <td>
      <%= image_tag product.image.tiny %>
    </td>
    <td>
      <h4><%= book.name %></h4>
      <br>
      <p><%= book.description %></p>
    </td>
    <td>
      <%= link_to remove_item_wishlist_path(book_id: book_id), class: 'btn btn-xs btn-danger', method: :delete do %>
      -
      <% end %>
      <%= quantity %>
      <%= link_to add_item_wishlist_path(book_id: book_id), class: 'btn btn-xs btn-success', method: :put do %>
      +
      <% end %>
    </td>
    <td>
      <%= item_total %>
    </td>
  </tr>
<% end %>

app/views/wishlists/show.html.erb
<section class="wishlist-show">
  <header class="page-header">
    <h1><%= @user.username %> Wishlist</h1>
    <h6>Isn't static yet, operates like Jungle's Cart</h6>
  </header>
  <% if @wishlist_total == 0 %>
  <div>
    <span>This user's wishlist is empty. Recommend <%= link_to 'some books', :root %>.</span>
  </div>
  <% else %>
  <div class="panel panel-default items">
    <table class="table table-bordered">
      <thead>
        <tr>
          <th colspan="2">Book</th>
          <th>List Price</th>
        </tr>
      </thead>
      <tbody>
        <% @wishlist_total = 0 %>
        <% wishlist.each do |book_id, details| %>
          <% render 'item', book_id: book_id, details: details %>
        <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4">
            Total:
          </th>
        </tr>
      </tfoot>
    </table>
  </div>
</section>
<% end %>