config/routes.rb
Rails.application.routes.draw do


  root to: 'books#index'

  resources :users, only: [:index, :show, :new, :edit, :update]

  resources :books, only: [:index, :show]

  resources :sessions, only: [:create]

  resources :bookstores, only: [:index]


  resource :favourites, only: [:show] do
    put    :add_item
  end

  resource :wishlist, only: [:show, :index] do
    put     :add_book
    delete  :remove_book
  end

  namespace :user do
    root to: 'users#show'
  end

  get '/login' => 'sessions#new'
  get '/classics' => 'classics#show'
  get '/provinces' => 'provinces#index'
  get '/feature/author' => 'featureds#index'
  get '/feature/publisher' => 'featureds#show'
  get '/search' => 'searches#search'


  post '/users' => 'users#index'
  get 'search' => 'books#search'

  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  get '/register' => 'users#new'
  post '/register' => 'users#create'

  get '/users' => 'users#index'
  get '/users/:user_id' => 'users#show'
  get '/users/:user_id/edit' => 'users#edit'
  get '/users/:id/wishlist' => 'wishlists#show'

  get 'favourites/favourites'
  get '/bookstores' => 'bookstores#index'

  get '/wishlist' => 'wishlist#show'


  get '/classics' => 'classics#show'




  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ActiveRecord::Base
  #belongs_to :author

  acts_as_favable

  has_one :pub_date
  has_many :genre
  has_one :publisher

  def average_rating
  	average = comments.map(&:rating)
  	average.reduce(:+) / average.size.to_f
  end

  def fave
  favable = Model.create
  favable.favorites.create(:url => "<%= book.image_link(:zoom => 5)")
  end

  def show
    favable = Model.find(1)
    favorites = favable.favorites.recent.limit(10).all
  end
end

app/models/bookstore.rb
class Bookstore < ApplicationRecord

end

app/models/genre.rb
class Genre < ActiveRecord::Base

  has_many :books

end

app/models/profile.rb
class Profile < ApplicationRecord

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  #mount_uploader :image, ProductImageUploader

  has_many :books

  #belongs_to :bookclub

  #has_one :wishlist

  has_one :profile

  validates :username, presence: true
  validates :email, presence: true
  # validates :location, presence: true

end

app/models/wishlist.rb
class Wishlist < ApplicationRecord

  belongs_to :user
  has_many :line_items

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def index
    @newest_books = GoogleBooks.search('Atlantic Canada',
                  {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc",
                    :count => 20,
                    :order_by => 'newest',
                    :order_by => 'relevance'})
  end

  def show

  end
end

app/controllers/home_controller.rb
# class GoogleBooksController < ActionController::Base
class HomeController < ApplicationController

  def index
  # @googlebooks = GoogleBooks.all
  puts 'ahhhhH!H!H!H'
    @newest_books = GoogleBooks.search('Nova Scotia', {:api_key => "AIzaSyCvKlUy4ZaVE_QxdMVZ7T37rTyEJZI-9Wc", :order_by => 'newest'})
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/bookstores_helper.rb
module BookstoresHelper
end

app/helpers/featureds_helper.rb
module FeaturedsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/provinces_helper.rb
module ProvincesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/_top_nav.html.erb
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa"  crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>


</head>
<body>
<nav class="navbar navbar-default" style="height: 75px; margin-bottom: 20px;">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="/"><%= image_tag("ReadAtlanticLessSmall.png", :style => "max-height: 85px;") %></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1" style="padding-top: 15px;">
      <ul class="nav navbar-nav">

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-weight: bold;">Discover Local Books <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/" data-no-turbolink='true'>New and Noteworthy</a></li>
            <li><a href="/classics" data-no-turbolink='true'>Atlantic Classics</a></li>
            <li><a href="/provinces" data-no-turbolink='true'>Browse by Province</a></li>
            <li><a href="#" data-no-turbolink='true'>Browse by Publisher</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/feature/author" data-no-turbolink='true'>Featured Author</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="/feature/publisher" data-no-turbolink='true'>Featured Publisher</a></li>
          </ul>
        </li>
        <li><a href="./bookstores" style="font-weight: bold;">Find Your Bookstore</a></li>
      </ul>
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-weight: bold;"><span class="glyphicon glyphicon-lock" aria-hidden="true"></span> My Books <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Wishlist", wishlist_path(current_user)%></li>
            <li><%= link_to "Favourites", 'favourites/favourites' %></li>
            <!--<li>Bookshelf</li> -->
          </ul>
        </li>
       <li><a href="./users" style="font-weight: bold;"><span class="glyphicon glyphicon-search" aria-hidden="true"></span> Find Friends</a></li>
       <li style="font-weight: bold;"><span class="glyphicon glyphicon-search" aria-hidden="true"></span><%= link_to "Find Friends", users_path %></li>

       <% if current_user %>
       <ul class="nav navbar-nav">
         <li class="dropdown">
           <a href="" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" style="font-weight: bold;"><span class="glyphicon glyphicon-user" aria-hidden="true"></span> Logged in as <%=current_user.username %><span class="caret"></span></a>
           <ul class="dropdown-menu">

             <li><%= link_to "Profile", current_user%></li>
             <li><%= link_to "Settings", edit_user_path(current_user)%></li>
             <li><a href="./logout" style="font-weight: bold;">Logout</a></li>

           </ul>
         </li>
       </ul>
       <% else %>
       <li><a href="./login" style="font-weight: bold;">Login</a></li>
       <% end %>
      </ul>
    </div>
  </div>
</nav>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Read Atlantic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/top_nav' %>

    <main class="container">
      <%= yield %>
    </main>
  </body>
</html>